# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 13:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dateo', '0003_auto_20151005_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dateos', to=settings.AUTH_USER_MODEL, verbose_name=b'User'),
        ),
    ]
