# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-14 14:34
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dateo', '0004_auto_20170522_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateo',
            name='geometry_collection',
            field=django.contrib.gis.db.models.fields.GeometryCollectionField(blank=True, null=True, spatial_index=False, srid=4326, verbose_name=b'GeometryCollection'),
        ),
    ]
