# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20151001_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('es', 'spanish'), ('en', 'english'), ('fr', 'french')], default='es', max_length=2, verbose_name='Language'),
        ),
    ]
