# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-20 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Facebook id'),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Twitter id'),
        ),
    ]
