# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-20 15:59
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_campaign_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='settings',
            field=jsonfield.fields.JSONField(blank=True, null=True, verbose_name=b'Settings'),
        ),
    ]
